version: '3'
services:
  db:
    image: 'postgres:15.3'
    environment:
      - 'POSTGRES_USER=whoami'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_DB=todolist'
    ports:
      - '5432:5432'
  app:
    image: 'ghcr.io/jaiiye/todo-app/todo-app:${TODO_APP_IMAGE_TAG:-latest}'
    ports:
      - "8080:8080"
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    volumes_from:
      - app
    depends_on:
      - app
